# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook_Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='link_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_ads.Tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_ads.Tag'),
        ),
        migrations.AddField(
            model_name='facebook_ad',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_ads.Image'),
        ),
        migrations.AddField(
            model_name='facebook_ad',
            name='link_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_ads.Link'),
        ),
    ]
