# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facebook_Ad',
            new_name='Ad',
        ),
    ]
