# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0002_auto_20180315_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='link_url',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_attribute',
        ),
        migrations.AddField(
            model_name='image',
            name='image_attribute',
            field=models.ManyToManyField(to='facebook_ads.Tag'),
        ),
        migrations.RemoveField(
            model_name='link',
            name='link_attribute',
        ),
        migrations.AddField(
            model_name='link',
            name='link_attribute',
            field=models.ManyToManyField(to='facebook_ads.Tag'),
        ),
    ]
