# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0003_auto_20180316_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_attribute',
        ),
        migrations.AddField(
            model_name='image',
            name='image_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_ads.Tag'),
        ),
        migrations.RemoveField(
            model_name='link',
            name='link_attribute',
        ),
        migrations.AddField(
            model_name='link',
            name='link_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_ads.Tag'),
        ),
        migrations.AddField(
            model_name='tag_link',
            name='link_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_ads.Link'),
        ),
        migrations.AddField(
            model_name='tag_link',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_ads.Tag'),
        ),
        migrations.AddField(
            model_name='tag_image',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_ads.Image'),
        ),
        migrations.AddField(
            model_name='tag_image',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_ads.Tag'),
        ),
    ]
