# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ads', '0004_auto_20180319_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_attribute',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link_attribute',
            new_name='attribute',
        ),
    ]
